server:
  port: 8090

#spring:
#  application:
#    name: springBatch
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 1056017312
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
batch:
  # ??????????sql
  job:
    # ??Spring Batch????????????????
    enabled: false
    names: parentjob
#  jdbc:
#    # spring batch??????????batch_
#    table-prefix: batch_
#    initialize-schema: always
#  sql:
#    init:
#      schema-locations: classpath:/org/springframework/batch/core/schema-mysql.sql
